version: '3'
services:
  schema-registry-ui:
    container_name: schema-registry-ui
    build:
      context: ..
      dockerfile: Dockerfile
    image: parrotstream/schema-registry-ui:0.9.5
    ports:
    - 8002:8002
    external_links:
    - kafka
    environment:
      SCHEMAREGISTRY_URL: http://kafka:8081
      PORT: 8002
      PROXY: "true"
      ALLOW_GLOBAL: "true"
      ALLOW_TRANSITIVE: "true"
      ALLOW_DELETION: "true"
networks:
  default:
    external:
      name: parrot_default
